"""add_team_ratings

Revision ID: 338f3c2ad8cb
Revises: f76ac4b8ea1b
Create Date: 2026-05-07 13:14:13.422969

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '338f3c2ad8cb'
down_revision = 'f76ac4b8ea1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###