"""bookmaker_intelligence

Revision ID: 835a19e09516
Revises: 4c1b3d303789
Create Date: 2026-05-11 12:46:01.196371

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '835a19e09516'
down_revision = '4c1b3d303789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker_intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=120), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('avg_odds', sa.Float(), nullable=False),
    sa.Column('survivability_score', sa.Float(), nullable=False),
    sa.Column('sharpness_score', sa.Float(), nullable=False),
    sa.Column('bookmaker_tier', sa.String(length=40), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmaker_intelligence_snapshots_bookmaker'), 'bookmaker_intelligence_snapshots', ['bookmaker'], unique=True)
    op.create_index(op.f('ix_bookmaker_intelligence_snapshots_bookmaker_tier'), 'bookmaker_intelligence_snapshots', ['bookmaker_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmaker_intelligence_snapshots_bookmaker_tier'), table_name='bookmaker_intelligence_snapshots')
    op.drop_index(op.f('ix_bookmaker_intelligence_snapshots_bookmaker'), table_name='bookmaker_intelligence_snapshots')
    op.drop_table('bookmaker_intelligence_snapshots')
    # ### end Alembic commands ###