"""advanced intelligence snapshots

Revision ID: 8814764f1982
Revises: 8f38380c2076
Create Date: 2026-05-09 10:42:55.968859

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8814764f1982'
down_revision = '8f38380c2076'
branch_labels = None
depends_on = None


def upgrade() -> None:

    indexes = [
        (
            'ix_league_intelligence_snapshots_prediction_allowed',
            'league_intelligence_snapshots',
            ['prediction_allowed'],
        ),
        (
            'ix_league_intelligence_snapshots_safe_for_accumulators',
            'league_intelligence_snapshots',
            ['safe_for_accumulators'],
        ),
        (
            'ix_league_intelligence_snapshots_verdict',
            'league_intelligence_snapshots',
            ['verdict'],
        ),
    ]

    for index_name, table_name, columns in indexes:
        try:
            op.create_index(
                index_name,
                table_name,
                columns,
                unique=False,
            )
        except Exception:
            pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_verdict'), table_name='odds_band_intelligence_snapshots')
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_prediction_allowed'), table_name='odds_band_intelligence_snapshots')
    op.alter_column('odds_band_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_market_intelligence_snapshots_verdict'), table_name='market_intelligence_snapshots')
    op.drop_index(op.f('ix_market_intelligence_snapshots_prediction_allowed'), table_name='market_intelligence_snapshots')
    op.alter_column('market_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'league_market_intelligence_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_verdict'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_season'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_prediction_allowed'), table_name='league_market_intelligence_snapshots')
    op.alter_column('league_market_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'league_intelligence_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_league_intelligence_snapshots_verdict'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_season'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_prediction_allowed'), table_name='league_intelligence_snapshots')
    op.alter_column('league_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_verdict'), table_name='confidence_band_intelligence_snapshots')
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_prediction_allowed'), table_name='confidence_band_intelligence_snapshots')
    op.alter_column('confidence_band_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###