"""add intelligence snapshot tables

Revision ID: 8f38380c2076
Revises: hist_bt_cache
Create Date: 2026-05-09 10:34:58.985482

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8f38380c2076'
down_revision = 'hist_bt_cache'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidence_band_intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('confidence_band', sa.String(), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('survivability_score', sa.Float(), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('prediction_allowed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_band_intelligence_snapshots_confidence_band'), 'confidence_band_intelligence_snapshots', ['confidence_band'], unique=False)
    op.create_index(op.f('ix_confidence_band_intelligence_snapshots_market'), 'confidence_band_intelligence_snapshots', ['market'], unique=False)
    op.create_table('league_market_intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('avg_odds', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('avg_value_score', sa.Float(), nullable=False),
    sa.Column('survivability_score', sa.Float(), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('prediction_allowed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_market_intelligence_snapshots_competition_id'), 'league_market_intelligence_snapshots', ['competition_id'], unique=False)
    op.create_index(op.f('ix_league_market_intelligence_snapshots_league'), 'league_market_intelligence_snapshots', ['league'], unique=False)
    op.create_index(op.f('ix_league_market_intelligence_snapshots_market'), 'league_market_intelligence_snapshots', ['market'], unique=False)
    op.create_index(op.f('ix_league_market_intelligence_snapshots_sport'), 'league_market_intelligence_snapshots', ['sport'], unique=False)
    op.create_table('market_intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('avg_odds', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('avg_value_score', sa.Float(), nullable=False),
    sa.Column('survivability_score', sa.Float(), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('prediction_allowed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_intelligence_snapshots_market'), 'market_intelligence_snapshots', ['market'], unique=False)
    op.create_index(op.f('ix_market_intelligence_snapshots_sport'), 'market_intelligence_snapshots', ['sport'], unique=False)
    op.create_table('odds_band_intelligence_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('odds_band', sa.String(), nullable=False),
    sa.Column('bets', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('survivability_score', sa.Float(), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('prediction_allowed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_band_intelligence_snapshots_market'), 'odds_band_intelligence_snapshots', ['market'], unique=False)
    op.create_index(op.f('ix_odds_band_intelligence_snapshots_odds_band'), 'odds_band_intelligence_snapshots', ['odds_band'], unique=False)
    op.create_index(op.f('ix_historical_backtest_bets_predicted_label'), 'historical_backtest_bets', ['predicted_label'], unique=False)
    op.add_column('league_intelligence_snapshots', sa.Column('bets', sa.Integer(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('hit_rate', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('roi', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('avg_odds', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('avg_confidence', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('avg_value_score', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('survivability_score', sa.Float(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('safe_for_accumulators', sa.Boolean(), nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('verdict', sa.String(), nullable=True))
    op.alter_column('league_intelligence_snapshots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_league_intelligence_snapshots_data_tier'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_prediction_allowed'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_risk_level'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_season'), table_name='league_intelligence_snapshots')
    op.drop_index(op.f('ix_league_intelligence_snapshots_training_allowed'), table_name='league_intelligence_snapshots')
    op.drop_constraint(op.f('uq_league_intel_sport_competition_season'), 'league_intelligence_snapshots', type_='unique')
    op.drop_constraint(op.f('league_intelligence_snapshots_competition_id_fkey'), 'league_intelligence_snapshots', type_='foreignkey')
    op.drop_column('league_intelligence_snapshots', 'data_tier')
    op.drop_column('league_intelligence_snapshots', 'training_allowed')
    op.drop_column('league_intelligence_snapshots', 'reason')
    op.drop_column('league_intelligence_snapshots', 'risk_level')
    op.drop_column('league_intelligence_snapshots', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_intelligence_snapshots', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('risk_level', sa.VARCHAR(length=40), server_default=sa.text("'high'::character varying"), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('league_intelligence_snapshots', sa.Column('training_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('data_tier', sa.VARCHAR(length=40), server_default=sa.text("'poor'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('league_intelligence_snapshots_competition_id_fkey'), 'league_intelligence_snapshots', 'competitions', ['competition_id'], ['id'])
    op.create_unique_constraint(op.f('uq_league_intel_sport_competition_season'), 'league_intelligence_snapshots', ['sport', 'competition_id', 'season'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_training_allowed'), 'league_intelligence_snapshots', ['training_allowed'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_season'), 'league_intelligence_snapshots', ['season'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_risk_level'), 'league_intelligence_snapshots', ['risk_level'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_prediction_allowed'), 'league_intelligence_snapshots', ['prediction_allowed'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_data_tier'), 'league_intelligence_snapshots', ['data_tier'], unique=False)
    op.alter_column('league_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('league_intelligence_snapshots', 'verdict')
    op.drop_column('league_intelligence_snapshots', 'safe_for_accumulators')
    op.drop_column('league_intelligence_snapshots', 'survivability_score')
    op.drop_column('league_intelligence_snapshots', 'avg_value_score')
    op.drop_column('league_intelligence_snapshots', 'avg_confidence')
    op.drop_column('league_intelligence_snapshots', 'avg_odds')
    op.drop_column('league_intelligence_snapshots', 'roi')
    op.drop_column('league_intelligence_snapshots', 'hit_rate')
    op.drop_column('league_intelligence_snapshots', 'bets')
    op.drop_index(op.f('ix_historical_backtest_bets_predicted_label'), table_name='historical_backtest_bets')
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_odds_band'), table_name='odds_band_intelligence_snapshots')
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_market'), table_name='odds_band_intelligence_snapshots')
    op.drop_table('odds_band_intelligence_snapshots')
    op.drop_index(op.f('ix_market_intelligence_snapshots_sport'), table_name='market_intelligence_snapshots')
    op.drop_index(op.f('ix_market_intelligence_snapshots_market'), table_name='market_intelligence_snapshots')
    op.drop_table('market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_sport'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_market'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_league'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_competition_id'), table_name='league_market_intelligence_snapshots')
    op.drop_table('league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_market'), table_name='confidence_band_intelligence_snapshots')
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_confidence_band'), table_name='confidence_band_intelligence_snapshots')
    op.drop_table('confidence_band_intelligence_snapshots')
    # ### end Alembic commands ###