"""add intelligence snapshot tables

Revision ID: 8f38380c2076
Revises: hist_bt_cache
Create Date: 2026-05-09 10:34:58.985482

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8f38380c2076'
down_revision = 'hist_bt_cache'
branch_labels = None
depends_on = None


def upgrade() -> None:

    # =========================================================
    # THESE TABLES ALREADY EXIST IN DB
    # =========================================================
    # confidence_band_intelligence_snapshots
    # odds_band_intelligence_snapshots
    # market_intelligence_snapshots
    # league_market_intelligence_snapshots
    #
    # We ONLY keep modifications that may still be needed.
    # =========================================================

    # historical_backtest_bets index
    try:
        op.create_index(
            op.f('ix_historical_backtest_bets_predicted_label'),
            'historical_backtest_bets',
            ['predicted_label'],
            unique=False,
        )
    except Exception:
        pass

    # =========================================================
    # LEAGUE INTELLIGENCE SNAPSHOT ALTERS
    # =========================================================

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('bets', sa.Integer(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('hit_rate', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('roi', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('avg_odds', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('avg_confidence', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('avg_value_score', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('survivability_score', sa.Float(), nullable=False, server_default='0'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('safe_for_accumulators', sa.Boolean(), nullable=False, server_default='false'),
        )
    except Exception:
        pass

    try:
        op.add_column(
            'league_intelligence_snapshots',
            sa.Column('verdict', sa.String(), nullable=True),
        )
    except Exception:
        pass

    # =========================================================
    # OPTIONAL CLEANUP
    # =========================================================

    try:
        op.alter_column(
            'league_intelligence_snapshots',
            'updated_at',
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            nullable=True,
        )
    except Exception:
        pass

    for index_name in [
        'ix_league_intelligence_snapshots_data_tier',
        'ix_league_intelligence_snapshots_prediction_allowed',
        'ix_league_intelligence_snapshots_risk_level',
        'ix_league_intelligence_snapshots_season',
        'ix_league_intelligence_snapshots_training_allowed',
    ]:
        try:
            op.drop_index(index_name, table_name='league_intelligence_snapshots')
        except Exception:
            pass

    try:
        op.drop_constraint(
            op.f('uq_league_intel_sport_competition_season'),
            'league_intelligence_snapshots',
            type_='unique',
        )
    except Exception:
        pass

    try:
        op.drop_constraint(
            op.f('league_intelligence_snapshots_competition_id_fkey'),
            'league_intelligence_snapshots',
            type_='foreignkey',
        )
    except Exception:
        pass

    for column_name in [
        'data_tier',
        'training_allowed',
        'reason',
        'risk_level',
        'created_at',
    ]:
        try:
            op.drop_column(
                'league_intelligence_snapshots',
                column_name,
            )
        except Exception:
            pass    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_intelligence_snapshots', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('risk_level', sa.VARCHAR(length=40), server_default=sa.text("'high'::character varying"), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('league_intelligence_snapshots', sa.Column('training_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('data_tier', sa.VARCHAR(length=40), server_default=sa.text("'poor'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('league_intelligence_snapshots_competition_id_fkey'), 'league_intelligence_snapshots', 'competitions', ['competition_id'], ['id'])
    op.create_unique_constraint(op.f('uq_league_intel_sport_competition_season'), 'league_intelligence_snapshots', ['sport', 'competition_id', 'season'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_training_allowed'), 'league_intelligence_snapshots', ['training_allowed'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_season'), 'league_intelligence_snapshots', ['season'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_risk_level'), 'league_intelligence_snapshots', ['risk_level'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_prediction_allowed'), 'league_intelligence_snapshots', ['prediction_allowed'], unique=False)
    op.create_index(op.f('ix_league_intelligence_snapshots_data_tier'), 'league_intelligence_snapshots', ['data_tier'], unique=False)
    op.alter_column('league_intelligence_snapshots', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('league_intelligence_snapshots', 'verdict')
    op.drop_column('league_intelligence_snapshots', 'safe_for_accumulators')
    op.drop_column('league_intelligence_snapshots', 'survivability_score')
    op.drop_column('league_intelligence_snapshots', 'avg_value_score')
    op.drop_column('league_intelligence_snapshots', 'avg_confidence')
    op.drop_column('league_intelligence_snapshots', 'avg_odds')
    op.drop_column('league_intelligence_snapshots', 'roi')
    op.drop_column('league_intelligence_snapshots', 'hit_rate')
    op.drop_column('league_intelligence_snapshots', 'bets')
    op.drop_index(op.f('ix_historical_backtest_bets_predicted_label'), table_name='historical_backtest_bets')
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_odds_band'), table_name='odds_band_intelligence_snapshots')
    op.drop_index(op.f('ix_odds_band_intelligence_snapshots_market'), table_name='odds_band_intelligence_snapshots')
    op.drop_table('odds_band_intelligence_snapshots')
    op.drop_index(op.f('ix_market_intelligence_snapshots_sport'), table_name='market_intelligence_snapshots')
    op.drop_index(op.f('ix_market_intelligence_snapshots_market'), table_name='market_intelligence_snapshots')
    op.drop_table('market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_sport'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_market'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_league'), table_name='league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_competition_id'), table_name='league_market_intelligence_snapshots')
    op.drop_table('league_market_intelligence_snapshots')
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_market'), table_name='confidence_band_intelligence_snapshots')
    op.drop_index(op.f('ix_confidence_band_intelligence_snapshots_confidence_band'), table_name='confidence_band_intelligence_snapshots')
    op.drop_table('confidence_band_intelligence_snapshots')
    # ### end Alembic commands ###