"""add_football_feature_snapshots

Revision ID: b46dd2830c1e
Revises: 338f3c2ad8cb
Create Date: 2026-05-07 13:42:33.781214

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b46dd2830c1e'
down_revision = '338f3c2ad8cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('football_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', name='uq_feature_snapshot_match')
    )
    op.create_index(op.f('ix_football_feature_snapshots_created_at'), 'football_feature_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_football_feature_snapshots_match_id'), 'football_feature_snapshots', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_football_feature_snapshots_match_id'), table_name='football_feature_snapshots')
    op.drop_index(op.f('ix_football_feature_snapshots_created_at'), table_name='football_feature_snapshots')
    op.drop_table('football_feature_snapshots')
    # ### end Alembic commands ###