"""add intelligence decay fields

Revision ID: d2904bb1275a
Revises: 8814764f1982
Create Date: 2026-05-09 11:11:32.868383

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd2904bb1275a'
down_revision = '8814764f1982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_intelligence_snapshots', sa.Column('recent_roi', sa.Float(), server_default='0', nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('recent_hit_rate', sa.Float(), server_default='0', nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('decay_factor', sa.Float(), server_default='1', nullable=False))
    op.add_column('league_intelligence_snapshots', sa.Column('stale', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_league_intelligence_snapshots_stale'), 'league_intelligence_snapshots', ['stale'], unique=False)
    op.add_column('league_market_intelligence_snapshots', sa.Column('recent_roi', sa.Float(), server_default='0', nullable=False))
    op.add_column('league_market_intelligence_snapshots', sa.Column('recent_hit_rate', sa.Float(), server_default='0', nullable=False))
    op.add_column('league_market_intelligence_snapshots', sa.Column('decay_factor', sa.Float(), server_default='1', nullable=False))
    op.add_column('league_market_intelligence_snapshots', sa.Column('stale', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_league_market_intelligence_snapshots_stale'), 'league_market_intelligence_snapshots', ['stale'], unique=False)
    op.add_column('market_intelligence_snapshots', sa.Column('recent_roi', sa.Float(), server_default='0', nullable=False))
    op.add_column('market_intelligence_snapshots', sa.Column('recent_hit_rate', sa.Float(), server_default='0', nullable=False))
    op.add_column('market_intelligence_snapshots', sa.Column('decay_factor', sa.Float(), server_default='1', nullable=False))
    op.add_column('market_intelligence_snapshots', sa.Column('stale', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_market_intelligence_snapshots_stale'), 'market_intelligence_snapshots', ['stale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_intelligence_snapshots_stale'), table_name='market_intelligence_snapshots')
    op.drop_column('market_intelligence_snapshots', 'stale')
    op.drop_column('market_intelligence_snapshots', 'decay_factor')
    op.drop_column('market_intelligence_snapshots', 'recent_hit_rate')
    op.drop_column('market_intelligence_snapshots', 'recent_roi')
    op.drop_index(op.f('ix_league_market_intelligence_snapshots_stale'), table_name='league_market_intelligence_snapshots')
    op.drop_column('league_market_intelligence_snapshots', 'stale')
    op.drop_column('league_market_intelligence_snapshots', 'decay_factor')
    op.drop_column('league_market_intelligence_snapshots', 'recent_hit_rate')
    op.drop_column('league_market_intelligence_snapshots', 'recent_roi')
    op.drop_index(op.f('ix_league_intelligence_snapshots_stale'), table_name='league_intelligence_snapshots')
    op.drop_column('league_intelligence_snapshots', 'stale')
    op.drop_column('league_intelligence_snapshots', 'decay_factor')
    op.drop_column('league_intelligence_snapshots', 'recent_hit_rate')
    op.drop_column('league_intelligence_snapshots', 'recent_roi')
    # ### end Alembic commands ###