"""add_team_ratings

Revision ID: f76ac4b8ea1b
Revises: 0006_market_reliability
Create Date: 2026-05-07 13:05:52.977435

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f76ac4b8ea1b'
down_revision = '0006_market_reliability'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=30), nullable=False),
    sa.Column('overall_elo', sa.Float(), nullable=False),
    sa.Column('attack_elo', sa.Float(), nullable=False),
    sa.Column('defense_elo', sa.Float(), nullable=False),
    sa.Column('form_elo', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('last_match_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'sport', name='uq_team_rating_team_sport')
    )
    op.create_index(op.f('ix_team_ratings_last_match_id'), 'team_ratings', ['last_match_id'], unique=False)
    op.create_index(op.f('ix_team_ratings_sport'), 'team_ratings', ['sport'], unique=False)
    op.create_index(op.f('ix_team_ratings_team_id'), 'team_ratings', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_ratings_updated_at'), 'team_ratings', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_stats_quality_snapshots_overall_score'), table_name='stats_quality_snapshots')
    op.drop_constraint(op.f('uq_stats_quality_sport_competition_season'), 'stats_quality_snapshots', type_='unique')
    op.create_unique_constraint('uq_stats_quality_sport_league_season', 'stats_quality_snapshots', ['sport', 'competition_id', 'season'])
    op.alter_column('team_match_stats', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'placeholder'::character varying"))
    op.alter_column('team_match_stats', 'is_real',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('team_match_stats', 'raw_stats_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('team_match_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_team_match_stats_is_real'), 'team_match_stats', ['is_real'], unique=False)
    op.create_index(op.f('ix_team_match_stats_source'), 'team_match_stats', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_match_stats_source'), table_name='team_match_stats')
    op.drop_index(op.f('ix_team_match_stats_is_real'), table_name='team_match_stats')
    op.alter_column('team_match_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_match_stats', 'raw_stats_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('team_match_stats', 'is_real',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('team_match_stats', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'placeholder'::character varying"))
    op.drop_constraint('uq_stats_quality_sport_league_season', 'stats_quality_snapshots', type_='unique')
    op.create_unique_constraint(op.f('uq_stats_quality_sport_competition_season'), 'stats_quality_snapshots', ['sport', 'competition_id', 'season'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_stats_quality_snapshots_overall_score'), 'stats_quality_snapshots', ['overall_score'], unique=False)
    op.drop_index(op.f('ix_team_ratings_updated_at'), table_name='team_ratings')
    op.drop_index(op.f('ix_team_ratings_team_id'), table_name='team_ratings')
    op.drop_index(op.f('ix_team_ratings_sport'), table_name='team_ratings')
    op.drop_index(op.f('ix_team_ratings_last_match_id'), table_name='team_ratings')
    op.drop_table('team_ratings')
    # ### end Alembic commands ###